version: '3.7'

services:
  es7:
    image: elasticsearch:7.17.6
    container_name: es7-${ID}
    environment:
      - node.name=es7-node
      - cluster.name=devh-cluster
      - cluster.initial_master_nodes=es7-node
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./log:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - devh-network
  kibana7:
    image: kibana:7.17.6
    container_name: kibana7-${ID}
    environment:
      - ELASTICSEARCH_HOSTS=["http://es7:9200"]
    ports:
      - '5601:5601'
    depends_on:
      - es7
    networks:
      - devh-network
  
      
networks:
  devh-network:
    external: true
