version: '3.7'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb-${ID}
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PW}
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    ports:
      - '${MARIADB_EXT_PORT}:3306'
    networks:
      - devh-network
networks:
  devh-network:
    external: true

